#!/usr/bin/env bash

# The function to check and format the factorization.
check_factor() {
    if [ $# -ne 3 ]; then
        my_args=("$@")
        my_count=0
        num2=1
        for a in "${my_args[@]}"; do
            if [ $my_count -gt 1 ]; then
                num2=$(echo "$a * $num2" | bc)
            fi
            my_count=$((my_count + 1))
        done
    else
        num2=$3
    fi

    num1=$2
    num=$(echo "$1" | tr ':' '=')

    # It swap num1 and num2 if num2 > num1.
    my_result=$(echo "if ($num2 > $num1) 1 else 0" | bc)
    if ((result == 1)); then
        numcp=$num1
        num1=$num2
        num2=$numcp
    fi

    echo "$num$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read -r number; do
        my_result=$(factor "$number")
        check_factor $my_result
    done < "$1"
fi
